### ISSUE TITLE
Who are MPs?

### ISSUE THREAD

**Issue by TomazErjavec** [calzada/PARLAMINT-ES-MC#13]
We mark each person as MP (and, if they are not so marked, they are not an MP). 

My assumptions is that if a speaker has 
```
<institution>
<ni country="ES">CD</ni>
</institution>
```

This means they are an MP. Is this correct?

If not, how do I know who is an MP?

**Comment by calzada** [comment]
Yes. They are MPs.And these MPs would include Members of Parliament and Members of the Government. If you want me to distinguish between them I could go through the list and change MPs for GOV (if you need me to be more specific). We did not need such a refined distinction. Because they all attend Parliament and are part of it. So I feel happy if all CD are MPs.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> So I feel happy if all CD are MPs.

I feel happy with this decision too!

**Comment by calzada** [comment]
Yes. Indeed, This is a good decision.
mc
